
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 1.04
name: Object-Signature
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  perl: 5.005
  Digest::MD5: 2.00
  Storable: 2.11
abstract: 
