---
abstract: 'Generate cryptographic signatures for objects'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Signature
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Digest::MD5: 2.00
  Storable: 2.11
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Object-Signature
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Object-Signature
version: 1.07
