abstract: ~
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Object-Signature
no_index: 
  directory: 
    - inc
    - t
requires: 
  Digest::MD5: 2.00
  Storable: 2.11
  perl: 5.005
version: 1.05
