name: Object-Signature
version: 0.02
abstract: Abstract base class for creating object signatures
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  prefork: 0.02
  Storable: 2.11
  Digest::MD5: 2.00
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
