name: Object-Signature
version: 1.03
abstract: 
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  Storable: 2.11
  Digest::MD5: 2.00
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
